### ISSUE TITLE
unregister `jquery.easing`, replace with `jquery-easing-original`

### ISSUE THREAD

**Issue by cvn** [bower/registry#165]
The `jquery.easing` bower package is out of date. The original author of [gdsmith/jquery.easing](https://github.com/gdsmith/jquery.easing) wants to claim the name but the package author is unresponsive: jozefizso/bower-jquery-easing#6

Can you unregister the current `jquery.easing` and rename `jquery-easing-original` to `jquery.easing`?

**Comment by desandro** [comment]
@gdsmith Rather than unregister `jquery.easing` to its current unofficial repo, the easiest solution would be to register the official under a different name. `jq.easing` is available.

Part of the issue is that `jozefizso/bower-jquery-easing` and `gdsmith/jquery.easing` have different file structures. Re-registering it could lead to errors. jozefizso's is on v1.3.1 and `gdsmith` is on v1.3.2, so they are within the same minor version.
